### ISSUE TITLE
Index out of range error when running the model

### ISSUE THREAD

**Issue by SeaCelo** [EAPD-DRB/OG-ZAF#43]
The model fails to run with a "list index out of range" error. Thanks to @jdebacker for [noticing it while testing a different issue](https://github.com/EAPD-DRB/OG-ZAF/pull/42#issuecomment-1690587040).

Trace below: 
```(ogzaf-dev-test) mlafleur@ProPro OG-ZAF % python examples/run_og_zaf.py
Number of workers =  7
making dir:  /Users/mlafleur/Projects/OG-ZAF/examples/OG-ZAF-Example/OUTPUT_BASELINE/SS
making dir:  /Users/mlafleur/Projects/OG-ZAF/examples/OG-ZAF-Example/OUTPUT_BASELINE/TPI
In runner, baseline is  True
SS using initial guess factors for r and TR of 1.0 and 1.0 , respectively.
Traceback (most recent call last):
  File "/Users/mlafleur/Projects/OG-ZAF/examples/run_og_zaf.py", line 127, in <module>
    main()
  File "/Users/mlafleur/Projects/OG-ZAF/examples/run_og_zaf.py", line 65, in main
    runner(p, time_path=True, client=client)
  File "/Users/mlafleur/opt/anaconda3/envs/ogzaf-dev-test/lib/python3.9/site-packages/ogcore/execute.py", line 45, in runner
    ss_outputs = SS.run_SS(p, client=client)
  File "/Users/mlafleur/opt/anaconda3/envs/ogzaf-dev-test/lib/python3.9/site-packages/ogcore/SS.py", line 1215, in run_SS
    sol = opt.root(
  File "/Users/mlafleur/opt/anaconda3/envs/ogzaf-dev-test/lib/python3.9/site-packages/scipy/optimize/_root.py", line 235, in root
    sol = _root_hybr(fun, x0, args=args, jac=jac, **options)
  File "/Users/mlafleur/opt/anaconda3/envs/ogzaf-dev-test/lib/python3.9/site-packages/scipy/optimize/_minpack_py.py", line 229, in _root_hybr
    shape, dtype = _check_func('fsolve', 'func', func, x0, args, n, (n,))
  File "/Users/mlafleur/opt/anaconda3/envs/ogzaf-dev-test/lib/python3.9/site-packages/scipy/optimize/_minpack_py.py", line 26, in _check_func
    res = atleast_1d(thefunc(*((x0[:numinputs],) + args)))
  File "/Users/mlafleur/opt/anaconda3/envs/ogzaf-dev-test/lib/python3.9/site-packages/ogcore/SS.py", line 1069, in SS_fsolve
    ) = inner_loop(outer_loop_vars, p, client)
  File "/Users/mlafleur/opt/anaconda3/envs/ogzaf-dev-test/lib/python3.9/site-packages/ogcore/SS.py", line 274, in inner_loop
    etr_params_3D = [
  File "/Users/mlafleur/opt/anaconda3/envs/ogzaf-dev-test/lib/python3.9/site-packages/ogcore/SS.py", line 275, in <listcomp>
    [
  File "/Users/mlafleur/opt/anaconda3/envs/ogzaf-dev-test/lib/python3.9/site-packages/ogcore/SS.py", line 276, in <listcomp>
    [p.etr_params[-1][s][i] for i in range(num_params)]
  File "/Users/mlafleur/opt/anaconda3/envs/ogzaf-dev-test/lib/python3.9/site-packages/ogcore/SS.py", line 276, in <listcomp>
    [p.etr_params[-1][s][i] for i in range(num_params)]
IndexError: list index out of range
```

cc: @gubenda

**Comment by SeaCelo** [comment]
fix in https://github.com/PSLmodels/OG-Core/issues/877
